//global font
import {Noto_Serif } from 'next/font/google'


//gobal page style
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer';


const notoserif = Noto_Serif({ subsets: ["latin"], weight: ["400"] });


export const metadata = {
  title: 'Flowers&Co.',
  description: 'Generated by create next app'
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoserif.className}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
